spring:
  datasource:
    username: root
    password: zhao123456
    url: jdbc:mysql://192.144.131.25:3306/fifth_group?serverTimezone=GMT&amp&useUnicode=true&amp&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: org.lanqiao.jd.entity,java.lang
#  type-aliases-package: java.lang
  mapper-locations: classpath:org/lanqiao/jd/mapper/*.xml
#  configuration:
#    cache-enabled: true

#showSql
logging:
  level:
    org.lanqiao.jd:
        mapper : debug
